version: "3.8"

services:
  mms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mms
    ports:
      - "80:80"
      - "1935:1935"
      - "1936:1936"
      - "443:443"
      - "554:554"
      - "555:555"
      - "8080:8080"
      - "8878:8878"
    volumes:
      - ~/workspace/0__repo/mms-server:/mnt/workspace/mms-server
    stdin_open: true      # 等价于 -it，支持交互
    tty: true
